_: add sudo shorthand

diff --git a/scripts/kmake b/scripts/kmake
--- a/scripts/kmake
+++ b/scripts/kmake
@@ -18,15 +18,20 @@ sparse_flag=''
 
 # cleanup traps
 function cleanup() {
-	local lines
-	lines="$(wc -l ../sparse.log.tmp 2>/dev/null | cut -f-1 -d' ')"
-	if [[ -z "$lines" ]]; then
-		lines=0
+	local build_lines error_lines
+	build_lines="$(wc -l ../build.log.tmp 2>/dev/null | cut -f-1 -d' ')"
+	error_lines="$(wc -l ../error.log.tmp 2>/dev/null | cut -f-1 -d' ')"
+	[[ -z "$build_lines" ]] && build_lines=0
+	[[ -z "$error_lines" ]] && error_lines=0
+	if ((build_lines > 5)); then
+		printf 'lines written to ../build.log: [%s]\n' "$build_lines"
+		cat ../build.log.tmp >>../build.log
 	fi
-	if ((lines > 5)); then
-		cat ../sparse.log.tmp >>../sparse.log
+	if ((error_lines > 5)); then
+		printf 'lines written to ../error.log: [%s]\n' "$error_lines"
+		cat ../error.log.tmp >>../error.log
 	fi
-	rm -f ../sparse.log.tmp
+	rm -f ../build.log.tmp ../error.log.tmp
 	cd "$save_dir" || exit 2
 	trap - INT ERR EXIT
 }
@@ -98,16 +103,25 @@ printf 'output directory: [%s]\n' \
 printf 'module directory: [%s]\n' \
 	"$(tput sgr0)$(tput setaf 13)$mod_dir$(tput sgr0)"
 
+# record date
+perl -e 'print "\n", "—"x72, "\nCompilation started at: ". `date`, "—"x72, "\n\n"' \
+	| tee -a ../build.log.tmp
+
 # start build
-if [[ -z "$sparse_flag" || "${make_cmd[1]}" == echo ]]; then
+if [[ -z "$sparse_flag" ]]; then
 	"${make_cmd[@]}" O="$out_dir" "${append_args[@]}"
 else
-	perl -e 'print "\n", "—"x72, "\nCompilation started at: ". `date`, "—"x72, "\n\n"' >>../sparse.log.tmp
-	"${make_cmd[@]}" O="$out_dir" "${append_args[@]}" 2>&1 >/dev/null | tee -a ../sparse.log.tmp
+	perl -e 'print "\n", "—"x72, "\nCompilation started at: ". `date`, "—"x72, "\n\n"' \
+		>> ../error.log.tmp
+	"${make_cmd[@]}" O="$out_dir" "${append_args[@]}" \
+		2> >(tee -a ../error.log.tmp >&2) \
+		> >(tee -a ../build.log.tmp)
 fi
 
 # install modules
 if [[ -n "${mod_args[*]}" ]]; then
 	rm -rfv "${mod_dir:?}"/*
-	"${make_cmd[@]}" O="$out_dir" "${mod_args[@]}"
+	"${make_cmd[@]}" O="$out_dir" "${mod_args[@]}" \
+		2> >(tee -a ../error.log.tmp >&2) \
+		> >(tee -a ../build.log.tmp)
 fi
