remove --squash flag from build commands

diff --git a/scripts/mkdocker b/scripts/mkdocker
--- a/scripts/mkdocker
+++ b/scripts/mkdocker
@@ -5,7 +5,7 @@ set -o errexit
 cwd="$PWD"
 
 trap '{ cd "$cwd"; printf "%s\n" "Done." >&2; }' EXIT
-trap '{ cd "$cwd; "printf "%s\n" "[$0:$LINENO] Docker build failed." >&2; }' ERR
+trap '{ cd "$cwd"; printf "%s\n" "[$0:$LINENO] Docker build failed." >&2; }' ERR
 
 export LIND_PREFIX="${LIND_PREFIX:-$HOME}"
 export LIND_BASE="${LIND_BASE:-$LIND_PREFIX/lind_project}"
@@ -20,7 +20,7 @@ export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-/lib/glibc}"
 cd "$LIND_BASE"
 
 docker image rm -f alyptik/lind:base alyptik/lind:prebuiltsdk alyptik/lind:naclruntime alyptik/lind:latest
-docker build --compress --squash --no-cache -t alyptik/lind:base ./docker/base
-docker build --compress --squash --no-cache -t alyptik/lind:prebuiltsdk ./docker/prebuiltsdk
-docker build --compress --squash --no-cache -t alyptik/lind:naclruntime ./docker/naclruntime
+docker build --compress --no-cache -t alyptik/lind:base ./docker/base
+docker build --compress --no-cache -t alyptik/lind:prebuiltsdk ./docker/prebuiltsdk
+docker build --compress --no-cache -t alyptik/lind:naclruntime ./docker/naclruntime
 docker build --compress --cache-from=alyptik/lind:naclruntime -t alyptik/lind:latest ./docker/naclruntime
